plugins:
  - jekyll-remote-theme
remote-theme: wbadart/jekyll-theme-dark-minimal
title: Juniper Inglis
description: Technologist. Tinkerer. Teacher.
email: juniperliketheberries@gmail.com
logo: /res/inglisj.jpeg
